#!/bin/bash
# gemini-research.sh — Run Gemini CLI as a parallel deep research source
# Usage: gemini-research.sh "research query" [output-dir] [timeout-seconds]
set -euo pipefail

QUERY="${1:?Usage: gemini-research.sh \"research query\" [output-dir] [timeout-seconds]}"
OUTPUT_DIR="${2:-$HOME/research-output}"
TIMEOUT="${3:-300}"

# Graceful skip if gemini CLI not found
if ! command -v gemini >/dev/null 2>&1; then
  echo "SKIP: gemini CLI not found — install via npm i -g @google/gemini-cli or see https://github.com/google-gemini/gemini-cli"
  exit 0
fi

# Cross-platform timeout: prefer gtimeout (macOS coreutils), then timeout (Linux), then fallback
if command -v gtimeout >/dev/null 2>&1; then
  TIMEOUT_CMD="gtimeout"
elif command -v timeout >/dev/null 2>&1; then
  TIMEOUT_CMD="timeout"
else
  TIMEOUT_CMD=""
fi

mkdir -p "$OUTPUT_DIR"

OUTPUT_FILE="$OUTPUT_DIR/gemini-deep-research.md"

PROMPT="You are a deep research agent with access to google_web_search.

CRITICAL: You MUST use google_web_search for EVERY major claim and topic.
Do NOT rely on your training data alone. Your training data may be outdated.
Always verify with live web search before stating any fact.
State your knowledge cutoff date at the start, then search for information beyond it.

RESEARCH QUERY:
$QUERY

INSTRUCTIONS:
1. Search the web FIRST for each major aspect before writing about it
2. Provide a comprehensive analysis covering all major aspects of this topic
3. Include specific facts, numbers, dates, and version numbers from web search results
4. Cite sources with URLs from your search results
5. Note areas of uncertainty or conflicting information
6. Highlight surprising or counterintuitive findings
7. Prefer recent information (last 12 months) unless historical context is needed
8. If web search returns no results for a claim, explicitly state it is from training data only

FORMAT your response as detailed research findings with clear sections and sub-sections.
For each section, list the web sources you consulted."

# Run gemini with timeout (or without if no timeout command available)
if [ -n "$TIMEOUT_CMD" ]; then
  GEMINI_CMD="$TIMEOUT_CMD $TIMEOUT gemini"
else
  GEMINI_CMD="gemini"
fi

if OUTPUT=$($GEMINI_CMD --output-format text "$PROMPT" 2>/dev/null); then
  cat > "$OUTPUT_FILE" <<HEADER
# Gemini Deep Research: $(echo "$QUERY" | head -c 80)

> Model: Gemini (via CLI) | Generated: $(date '+%Y-%m-%d %H:%M')

## Findings

$OUTPUT

---
*Generated by gemini-research.sh | Gemini CLI $(gemini --version 2>/dev/null || echo "unknown")*
HEADER
  echo "OK: Gemini research written to $OUTPUT_FILE"
else
  EXIT_CODE=$?
  if [ "$EXIT_CODE" -eq 124 ]; then
    echo "TIMEOUT: Gemini research exceeded ${TIMEOUT}s limit"
    cat > "$OUTPUT_FILE" <<HEADER
# Gemini Deep Research: $(echo "$QUERY" | head -c 80)

> Status: TIMEOUT after ${TIMEOUT}s

## Note
Gemini research timed out. Partial results may not be available.

---
*Generated by gemini-research.sh | Timed out*
HEADER
  else
    echo "ERROR: Gemini CLI failed with exit code $EXIT_CODE"
    exit 0  # Graceful — don't block the rest of the pipeline
  fi
fi
